version: "3.8"

services:
  backend:
    build: .
    environment:
      - IS_DOCKER=true
      - DB_URL=postgresql://postgres:postgres@postgres:${DB_PORT}/quizzes
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "${APP_PORT}:${APP_PORT}"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizzes
    networks:
      - app_network
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-p", "${DB_PORT}"]
      interval: 5s
      retries: 5
    command: ["postgres", "-p", "${DB_PORT}"]

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
