version: "3.8"

services:
  backend:
    build: .
    environment:
      - IS_DOCKER=true
      - DB_URL=postgresql://postgres:postgres@postgres:5432/quizzes
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "5000:5000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizzes
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
