"""Describe your changes

Revision ID: 0dff4a620590
Revises: d8012b435491
Create Date: 2025-03-24 11:56:42.984970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dff4a620590'
down_revision = 'd8012b435491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint('quizzes_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quizzes_student_id_fkey', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
