"""Describe your changes

Revision ID: 117b2a6fcc68
Revises: d398708d173c
Create Date: 2025-03-24 21:20:39.328233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117b2a6fcc68'
down_revision = 'd398708d173c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_template_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'quiz_template_items', ['quiz_template_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quiz_template_item_id')

    # ### end Alembic commands ###
