"""Describe your changes

Revision ID: 2b646ed40989
Revises: 8ac078f85277
Create Date: 2025-03-20 20:31:48.248862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b646ed40989'
down_revision = '8ac078f85277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.alter_column('feedback_type',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.alter_column('feedback_type',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
