"""Uprava

Revision ID: 62970309421d
Revises: 
Create Date: 2024-12-13 13:00:54.794930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62970309421d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_category')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stug', sa.String(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('stug')

    op.create_table('question_category',
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'category_id')
    )
    # ### end Alembic commands ###
