"""Describe your changes

Revision ID: 6eed5231fa09
Revises: 2360cb4d60d8
Create Date: 2025-02-25 21:51:45.657283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eed5231fa09'
down_revision = '2360cb4d60d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_template_item_questions_association',
    sa.Column('quiz_template_item_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_template_item_id'], ['quiz_template_items.id'], ),
    sa.PrimaryKeyConstraint('quiz_template_item_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_template_item_questions_association')
    # ### end Alembic commands ###
