"""Describe your changes

Revision ID: 8ac078f85277
Revises: f20eb5f79d43
Create Date: 2025-03-20 20:17:17.604325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac078f85277'
down_revision = 'f20eb5f79d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
