"""Describe your changes

Revision ID: 9bdf938d3a17
Revises: 2b646ed40989
Create Date: 2025-03-21 12:05:04.705260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdf938d3a17'
down_revision = '2b646ed40989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_type_after_close', sa.ARRAY(sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.drop_column('feedback_type_after_close')

    # ### end Alembic commands ###
