"""pridanie is_correct do Answer

Revision ID: bb0c6b22824a
Revises: 62970309421d
Create Date: 2024-12-25 11:11:42.563056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0c6b22824a'
down_revision = '62970309421d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_single', sa.Boolean(), nullable=True))

    with op.batch_alter_table('short_answers', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_column('is_single')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
