"""Describe your changes

Revision ID: cd25e28b8013
Revises: 019794a2e1cf
Create Date: 2025-02-25 20:57:38.453300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd25e28b8013'
down_revision = '019794a2e1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.drop_constraint('quiz_template_items_quiz_template_id_fkey', type_='foreignkey')
        batch_op.drop_column('quiz_template_id')

    with op.batch_alter_table('quiz_template_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_template_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('quiz_template_section_quiz_template_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz_templates', ['quiz_template_id'], ['id'])
        batch_op.drop_column('quiz_template_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_template_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_template_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quiz_template_section_quiz_template_item_id_fkey', 'quiz_template_items', ['quiz_template_item_id'], ['id'])
        batch_op.drop_column('quiz_template_id')

    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_template_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('quiz_template_items_quiz_template_id_fkey', 'quiz_templates', ['quiz_template_id'], ['id'])

    # ### end Alembic commands ###
