"""Describe your changes

Revision ID: ec346b56a268
Revises: bb0c6b22824a
Create Date: 2025-02-25 20:22:28.662061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec346b56a268'
down_revision = 'bb0c6b22824a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_template_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('quiz_template_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_template_item_id'], ['quiz_template_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluate', sa.Integer(), nullable=True))

    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('shuffle_sections', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('correction_of_attempts', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('number_of_corrections', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('datetime_check', sa.DateTime(), nullable=True))
        batch_op.drop_column('number_of_attempts')
        batch_op.drop_column('filter_on_question')
        batch_op.drop_column('correctable_attempts')
        batch_op.drop_column('random_order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_order', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('correctable_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filter_on_question', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('number_of_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('datetime_check')
        batch_op.drop_column('number_of_corrections')
        batch_op.drop_column('correction_of_attempts')
        batch_op.drop_column('shuffle_sections')
        batch_op.drop_column('title')

    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.drop_column('evaluate')

    op.drop_table('quiz_template_section')
    # ### end Alembic commands ###
