"""Describe your changes

Revision ID: 00275b308383
Revises: f9e38150576c
Create Date: 2025-03-06 21:08:01.688106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00275b308383'
down_revision = 'f9e38150576c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('students_comment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teachers_comment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_section_id', sa.Integer(), nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_constraint('quiz_items_quiz_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz_sections', ['quiz_section_id'], ['id'])
        batch_op.create_foreign_key(None, 'comments', ['teachers_comment_id'], ['id'])
        batch_op.create_foreign_key(None, 'comments', ['students_comment_id'], ['id'])
        batch_op.drop_column('quiz_id')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('order')

    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quiz_items_quiz_id_fkey', 'quizzes', ['quiz_id'], ['id'])
        batch_op.alter_column('score',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('quiz_section_id')
        batch_op.drop_column('teachers_comment_id')
        batch_op.drop_column('students_comment_id')

    op.drop_table('quiz_sections')
    # ### end Alembic commands ###
