"""Describe your changes

Revision ID: 019794a2e1cf
Revises: ec346b56a268
Create Date: 2025-02-25 20:27:45.238603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019794a2e1cf'
down_revision = 'ec346b56a268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
