"""Describe your changes

Revision ID: 05788f5689f1
Revises: b838c97f0f9b
Create Date: 2025-03-13 21:16:04.603269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05788f5689f1'
down_revision = 'b838c97f0f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
