"""Auto migration

Revision ID: 2cc4683a286d
Revises: ffbee5717f08
Create Date: 2025-04-05 16:48:00.718595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cc4683a286d'
down_revision = 'ffbee5717f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.alter_column('datetime_check',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.alter_column('datetime_check',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###
