"""Describe your changes

Revision ID: 323af2653e5e
Revises: f991185979b2
Create Date: 2025-05-22 17:09:04.818822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323af2653e5e'
down_revision = 'f991185979b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_template', sa.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sections', schema=None) as batch_op:
        batch_op.drop_column('order_template')

    # ### end Alembic commands ###
