"""Describe your changes

Revision ID: 44a862a24241
Revises: de2b7824727e
Create Date: 2025-05-28 19:06:07.690853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a862a24241'
down_revision = 'de2b7824727e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multiple_choice_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distractors', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multiple_choice_questions', schema=None) as batch_op:
        batch_op.drop_column('distractors')

    # ### end Alembic commands ###
