"""Describe your changes

Revision ID: 4d2035d20e49
Revises: 2cc4683a286d
Create Date: 2025-04-07 22:20:52.073055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2035d20e49'
down_revision = '2cc4683a286d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_template_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'quiz_template_items', ['quiz_template_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quiz_template_item_id')

    # ### end Alembic commands ###
