"""Describe your changes

Revision ID: 575f59c76175
Revises: 6eed5231fa09
Create Date: 2025-02-25 21:58:32.919640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575f59c76175'
down_revision = '6eed5231fa09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_template_item_questions_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluate', sa.Integer(), nullable=True))

    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_column('evaluate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluate', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('order')

    with op.batch_alter_table('quiz_template_item_questions_association', schema=None) as batch_op:
        batch_op.drop_column('evaluate')

    # ### end Alembic commands ###
