"""Describe your changes

Revision ID: 656d58826239
Revises: 7c0b7d44b057
Create Date: 2025-03-25 17:52:13.657125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656d58826239'
down_revision = '7c0b7d44b057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_points', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('achieved_points', sa.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('achieved_points')
        batch_op.drop_column('max_points')

    # ### end Alembic commands ###
