"""Describe your changes

Revision ID: 7976aab97f8e
Revises: 575f59c76175
Create Date: 2025-02-27 19:58:15.092775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7976aab97f8e'
down_revision = '575f59c76175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_template_item_questions_association')
    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'quiz_templates', ['quiz_template_id'], ['id'])
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quiz_template_id')
        batch_op.drop_column('evaluate')

    op.create_table('quiz_template_item_questions_association',
    sa.Column('quiz_template_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evaluate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='quiz_template_item_questions_association_question_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_template_item_id'], ['quiz_template_items.id'], name='quiz_template_item_questions_associa_quiz_template_item_id_fkey'),
    sa.PrimaryKeyConstraint('quiz_template_item_id', 'question_id', name='quiz_template_item_questions_association_pkey')
    )
    # ### end Alembic commands ###
