"""Describe your changes

Revision ID: 7c0b7d44b057
Revises: 117b2a6fcc68
Create Date: 2025-03-24 22:09:00.496305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0b7d44b057'
down_revision = '117b2a6fcc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_points', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_constraint('quiz_items_quiz_template_item_id_fkey', type_='foreignkey')
        batch_op.drop_column('quiz_template_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_template_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('quiz_items_quiz_template_item_id_fkey', 'quiz_template_items', ['quiz_template_item_id'], ['id'])
        batch_op.drop_column('max_points')

    # ### end Alembic commands ###
