"""Describe your changes

Revision ID: d7fd413d2ac4
Revises: 44a862a24241
Create Date: 2025-05-28 19:07:15.515968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7fd413d2ac4'
down_revision = '44a862a24241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matching_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distractors', sa.ARRAY(sa.String()), nullable=True))

    with op.batch_alter_table('multiple_choice_questions', schema=None) as batch_op:
        batch_op.drop_column('distractors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multiple_choice_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distractors', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    with op.batch_alter_table('matching_questions', schema=None) as batch_op:
        batch_op.drop_column('distractors')

    # ### end Alembic commands ###
