"""Describe your changes

Revision ID: de2b7824727e
Revises: 323af2653e5e
Create Date: 2025-05-22 17:26:10.161807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de2b7824727e'
down_revision = '323af2653e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sections', schema=None) as batch_op:
        batch_op.drop_column('order_template')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_template', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
