"""Describe your changes

Revision ID: e797bf548141
Revises: 4d2035d20e49
Create Date: 2025-04-07 22:56:38.148811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e797bf548141'
down_revision = '4d2035d20e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.drop_constraint('quiz_items_quiz_template_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz_template_items', ['quiz_template_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quiz_items_quiz_template_item_id_fkey', 'quiz_template_items', ['quiz_template_item_id'], ['id'])

    # ### end Alembic commands ###
