"""Describe your changes

Revision ID: f20eb5f79d43
Revises: 05788f5689f1
Create Date: 2025-03-17 10:44:55.169229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20eb5f79d43'
down_revision = '05788f5689f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_templates', schema=None) as batch_op:
        batch_op.drop_column('feedback_type')

    # ### end Alembic commands ###
