"""Auto migration

Revision ID: ffbee5717f08
Revises: f1682a1bb825
Create Date: 2025-04-05 16:36:24.858419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbee5717f08'
down_revision = 'f1682a1bb825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('skuska')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skuska', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
